#!/bin/sh
mkdir -p /var/mobile/Library/iWidgets
cp -r /Library/Application\ Support/Troy/iWidgets.bundle/* /var/mobile/Library/iWidgets/
rm -r /Library/Application\ Support/Troy
chmod -R 775 /var/mobile/Library/iWidgets
chmod -R 775 /var/mobile/Library/iWidgets/HS13*
echo "Thank you for installing HS13!"
echo "A special thank you to @QuixThe2nd & @Jamie_Devvix for all their help"
echo "This widget is protected by TroyDRM. Contact @QuixThe2nd for more information"
exit 0
