#!/bin/sh
if [[ -d "/var/mobile/Library/iWidgets/HS13" ]]; then
    rm -r "/var/mobile/Library/iWidgets/HS13"
fi
if [[ -d "/var/mobile/Library/iWidgets/HS13 (2)" ]]; then
    rm -r "/var/mobile/Library/iWidgets/HS13 (2)"
fi
if [[ -d "/var/mobile/Library/iWidgets/HS13 SE" ]]; then
    rm -r "/var/mobile/Library/iWidgets/HS13 SE"
fi
if [[ -d "/var/mobile/Library/iWidgets/HS13 SE (2)" ]]; then
    rm -r "/var/mobile/Library/iWidgets/HS13 SE (2)"
fi
exit 0
